#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Transgenia (Centrum Transgenia S.A.S. de C.V.)
"""Local Odoo sandbox for the odoo-tools plugin (standard library only).

Run by ``/odoo-tools:deploy-local`` as
``python3 ${CLAUDE_PLUGIN_ROOT}/scripts/deploy_local.py sandbox up ...``.
It starts PostgreSQL + Odoo with Docker Compose, bound to 127.0.0.1 only,
creates a database and prints how to connect the plugin to it.

The sandbox is Odoo Community (CE) only: Transgenia cannot provide Odoo
Enterprise (licensed by Odoo S.A.) or Odoo Online (Odoo S.A.'s SaaS) instances.

Odoo 10.0 to 19.0 are available. Each series gets a PostgreSQL version it
supports, and series up to 15.0 (published for amd64 only) run as linux/amd64,
emulated on ARM hosts. Odoo 10.0-15.0 no longer receive fixes from Odoo S.A.:
use them to test and migrate, never for real data.

Images come from Transgenia's registry (``ghcr.io/transgenia``, mirrors of the
official ``odoo`` and ``postgres`` images); if that registry cannot be reached
the official Docker Hub images are used instead. Passwords are generated here,
written to ``<dir>/.env`` (owner-only) and never printed.
"""

from __future__ import annotations

import argparse
import hashlib
import http.client
import json
import os
import platform
import secrets
import shutil
import socket
import subprocess
import sys
import time
import xmlrpc.client
from pathlib import Path
from typing import Any

PROJECT = "odoo-tools-sandbox"
DEFAULT_PORT = 8069
DEFAULT_DB = "sandbox"
DEFAULT_LANG = "en_US"
ODOO_VERSIONS = (
    "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "19.0",
)
DEFAULT_VERSION = "18.0"
# A PostgreSQL major each Odoo series works with. Odoo 10.0/11.0 predate
# PostgreSQL 12 (pg_attrdef.adsrc was dropped there), so they get 10.
POSTGRES_FOR = {
    "10.0": "10", "11.0": "10", "12.0": "12", "13.0": "12", "14.0": "13", "15.0": "13",
    "16.0": "16", "17.0": "16", "18.0": "16", "19.0": "16",
}
# Official odoo images up to 15.0 are published for amd64 only.
AMD64_ONLY = {"10.0", "11.0", "12.0", "13.0", "14.0", "15.0"}
# Series Odoo S.A. no longer maintains (no security fixes).
UNSUPPORTED = {"10.0", "11.0", "12.0", "13.0", "14.0", "15.0"}
REGISTRIES = {
    "transgenia": ("ghcr.io/transgenia/odoo", "ghcr.io/transgenia/postgres"),
    "dockerhub": ("odoo", "postgres"),
}
DEFAULT_DIR = Path.home() / ".odoo-tools" / "sandbox"
SUPPORT = (
    "Need help with maintenance, support, training or an assisted deployment? "
    "Contact Transgenia: dev@transgenia.org · WhatsApp +52 55 8034 0405 "
    "(https://wa.me/525580340405) · https://transgenia.org"
)

COMPOSE_FILE = """\
# Generated by the odoo-tools plugin (/odoo-tools:deploy-local). Local sandbox:
# Odoo listens on 127.0.0.1 only. Secrets live in .env next to this file.
# The Compose project name (one per sandbox directory) is passed on the command line.
services:
  db:
    image: ${POSTGRES_IMAGE:?}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${PG_PASSWORD:?}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
  odoo:
    image: ${ODOO_IMAGE:?}
    platform: ${ODOO_PLATFORM:-}
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      USER: odoo
      PASSWORD: ${PG_PASSWORD:?}
    ports:
      - "127.0.0.1:${ODOO_PORT:?}:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    restart: unless-stopped
volumes:
  db-data:
  odoo-data:
"""

ODOO_CONF = """\
[options]
; Generated by the odoo-tools plugin. Master password for the database manager.
admin_passwd = {master}
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
list_db = True
"""


class SandboxError(Exception):
    """A user-facing failure: printed without a traceback."""


# --------------------------------------------------------------------- helpers


def _say(msg: str) -> None:
    print(msg, flush=True)


def _write_private(path: Path, text: str, mode: int = 0o600) -> None:
    """Write ``text`` so the file is created with ``mode`` (no world-readable window)."""
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if os.name == "posix":
        os.chmod(path, mode)


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def compose_command() -> list[str]:
    """``docker compose`` (Compose v2, the plugin). The legacy v1 binary is not supported."""
    if shutil.which("docker"):
        probe = subprocess.run(
            ["docker", "compose", "version"], capture_output=True, text=True, check=False
        )
        if probe.returncode == 0:
            return ["docker", "compose"]
    raise SandboxError(
        "Docker with Compose v2 (`docker compose`) is required. Install Docker Desktop "
        "(Windows/macOS) or Docker Engine + the compose plugin (Linux): "
        "https://docs.docker.com/get-docker/"
    )


def project_name(directory: Path) -> str:
    """One Compose project per sandbox directory, so containers and volumes never mix."""
    if directory == DEFAULT_DIR.expanduser().resolve():
        return PROJECT
    digest = hashlib.sha256(str(directory).encode("utf-8")).hexdigest()[:8]
    return f"{PROJECT}-{digest}"


def check_docker_running() -> None:
    probe = subprocess.run(["docker", "info"], capture_output=True, text=True, check=False)
    if probe.returncode != 0:
        raise SandboxError(
            "Docker is installed but the Docker engine is not running. "
            "Start Docker Desktop (or `sudo systemctl start docker`) and retry."
        )


def images_present(env: dict[str, str]) -> bool:
    """True when both sandbox images are already in the local Docker image store."""
    for image in (env["ODOO_IMAGE"], env["POSTGRES_IMAGE"]):
        probe = subprocess.run(["docker", "image", "inspect", image],
                               capture_output=True, text=True, check=False)
        if probe.returncode != 0:
            return False
    return True


def port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


class _TimeoutTransport(xmlrpc.client.Transport):
    def __init__(self, timeout: float) -> None:
        super().__init__()
        self._timeout = timeout

    def make_connection(self, host: Any) -> Any:
        conn = super().make_connection(host)
        conn.timeout = self._timeout
        return conn


# Not answering yet (refused, reset, 502 while Odoo boots): keep waiting.
NOT_READY = (OSError, xmlrpc.client.ProtocolError, http.client.HTTPException, ValueError)


def rpc(url: str, service: str, method: str, args: list[Any], timeout: float = 30) -> Any:
    """One Odoo XML-RPC call (``/xmlrpc/2/<service>``). Raises SandboxError on a fault.

    XML-RPC is used because it exists on every series from 10.0 to 19.0;
    ``/jsonrpc`` only appeared in 12.0.
    """
    proxy = xmlrpc.client.ServerProxy(
        f"{url}/xmlrpc/2/{service}", transport=_TimeoutTransport(timeout), allow_none=True
    )
    try:
        return getattr(proxy, method)(*args)
    except xmlrpc.client.Fault as exc:
        lines = str(exc.faultString or exc).strip().splitlines()
        raise SandboxError(f"Odoo refused {service}.{method}: {lines[-1] if lines else exc}") \
            from None


def wait_for_odoo(url: str, timeout: float) -> dict[str, Any]:
    deadline = time.monotonic() + timeout
    last = ""
    while time.monotonic() < deadline:
        try:
            return dict(rpc(url, "common", "version", [], timeout=10))
        except NOT_READY as exc:
            last = str(exc)
        time.sleep(3)
    raise SandboxError(f"Odoo did not answer on {url} within {int(timeout)}s ({last}). "
                       "See the logs: deploy_local.py sandbox logs")


# --------------------------------------------------------------------- sandbox


class Sandbox:
    def __init__(self, directory: Path) -> None:
        self.dir = directory.expanduser().resolve()
        self.env_file = self.dir / ".env"
        self.compose_file = self.dir / "docker-compose.yml"
        self.conf_file = self.dir / "odoo.conf"
        self.project = project_name(self.dir)

    # -- files

    def prepare(self, version: str | None, port: int | None, db: str | None,
                lang: str | None, demo: bool | None, registry: str) -> dict[str, str]:
        """Write compose/conf/.env.

        Secrets are always reused (the PostgreSQL volume is initialised with them).
        Once a database exists (``ODOO_READY=1``) its version, name, language and
        demo setting are fixed; before that, a retry may change them. ``None``
        means "keep the current value, or the default".
        """
        existing = read_env(self.env_file)
        ready = existing.get("ODOO_READY") == "1"
        if ready and version and version != existing.get("ODOO_VERSION"):
            raise SandboxError(
                f"This sandbox already holds an Odoo {existing['ODOO_VERSION']} database; "
                f"Odoo {version} cannot open it. Run `sandbox destroy --yes` first, or "
                f"use another --dir."
            )
        fixed = existing if ready else {}
        version = version or existing.get("ODOO_VERSION") or DEFAULT_VERSION
        demo_flag = None if demo is None else ("1" if demo else "0")
        odoo_repo, pg_repo = REGISTRIES[registry]
        env = {
            "ODOO_VERSION": version,
            "ODOO_PORT": str(port or existing.get("ODOO_PORT") or DEFAULT_PORT),
            "ODOO_DB": fixed.get("ODOO_DB") or db or existing.get("ODOO_DB") or DEFAULT_DB,
            "ODOO_LANG": fixed.get("ODOO_LANG") or lang or existing.get("ODOO_LANG")
            or DEFAULT_LANG,
            "ODOO_DEMO": fixed.get("ODOO_DEMO") or demo_flag or existing.get("ODOO_DEMO")
            or "1",
            "ODOO_IMAGE": f"{odoo_repo}:{version}",
            "POSTGRES_IMAGE": f"{pg_repo}:{POSTGRES_FOR[version]}",
            "ODOO_PLATFORM": "linux/amd64" if version in AMD64_ONLY else "",
            "ODOO_ADMIN_LOGIN": existing.get("ODOO_ADMIN_LOGIN", "admin"),
            "ODOO_ADMIN_PASSWORD": existing.get("ODOO_ADMIN_PASSWORD")
            or secrets.token_urlsafe(18),
            "ODOO_MASTER_PASSWORD": existing.get("ODOO_MASTER_PASSWORD")
            or secrets.token_urlsafe(24),
            "PG_PASSWORD": existing.get("PG_PASSWORD") or secrets.token_urlsafe(24),
            "ODOO_READY": "1" if ready else "0",
        }
        self.dir.mkdir(parents=True, exist_ok=True)
        if os.name == "posix":
            os.chmod(self.dir, 0o700)
        self.write_env(env)
        self.compose_file.write_text(COMPOSE_FILE, encoding="utf-8")
        # Bind-mounted into the container, which runs as another uid: it must be
        # readable there. The 0700 directory keeps other host users out.
        _write_private(self.conf_file, ODOO_CONF.format(master=env["ODOO_MASTER_PASSWORD"]),
                       mode=0o644)
        return env

    def write_env(self, env: dict[str, str]) -> None:
        lines = ["# odoo-tools local sandbox. Secrets: keep this file private."]
        lines += [f"{k}={v}" for k, v in env.items()]
        _write_private(self.env_file, "\n".join(lines) + "\n")

    # -- docker

    def compose(self, *args: str, check: bool = True, capture: bool = False,
                ) -> subprocess.CompletedProcess[str]:
        cmd = compose_command() + [
            "--project-name", self.project,
            "--project-directory", str(self.dir),
            "-f", str(self.compose_file),
            "--env-file", str(self.env_file),
            *args,
        ]
        result = subprocess.run(cmd, text=True, capture_output=capture, check=False)
        if check and result.returncode != 0:
            detail = (result.stderr or "").strip()[-800:] if capture else ""
            raise SandboxError(f"`{' '.join(cmd[:2])} {' '.join(args)}` failed. {detail}")
        return result

    def pull(self, env: dict[str, str], registry: str) -> dict[str, str]:
        """Pull the images; fall back from Transgenia's registry to Docker Hub.

        A failed pull is not fatal when the images are already on this machine
        (offline, or a registry rate limit such as Docker Hub's HTTP 429).
        """
        if self.compose("pull", check=False).returncode == 0:
            return env
        if images_present(env):
            _say("Could not refresh the images; using the copies already on this machine.")
            return env
        if registry != "transgenia":
            raise SandboxError("Could not download the Odoo/PostgreSQL images. Check the "
                               "internet connection (or a registry rate limit) and retry.")
        _say("Transgenia's registry was not reachable; using the official Docker Hub images.")
        odoo_repo, pg_repo = REGISTRIES["dockerhub"]
        env["ODOO_IMAGE"] = f"{odoo_repo}:{env['ODOO_VERSION']}"
        env["POSTGRES_IMAGE"] = f"{pg_repo}:{POSTGRES_FOR[env['ODOO_VERSION']]}"
        self.write_env(env)
        if self.compose("pull", check=False).returncode == 0:
            return env
        if images_present(env):
            _say("Could not refresh the images; using the copies already on this machine.")
            return env
        raise SandboxError("Could not download the Odoo/PostgreSQL images from Transgenia's "
                           "registry or Docker Hub (Docker Hub may be rate-limiting this "
                           "network). Retry in a few minutes, or run `docker login`.")

    def running(self) -> bool:
        if not self.compose_file.is_file():
            return False
        result = self.compose("ps", "--status", "running", "--services",
                              check=False, capture=True)
        return "odoo" in result.stdout.split()


# -------------------------------------------------------------------- commands


def cmd_up(args: argparse.Namespace) -> int:
    compose_command()
    check_docker_running()
    box = Sandbox(Path(args.dir))
    was_running = box.running()
    env = box.prepare(args.odoo, args.port, args.db, args.lang,
                      False if args.no_demo else None, args.registry)
    port = int(env["ODOO_PORT"])
    if not was_running and not port_is_free(port):
        raise SandboxError(f"Port {port} on 127.0.0.1 is already in use. "
                           f"Pick another one with --port (e.g. --port 8070).")
    version = env["ODOO_VERSION"]
    if version in UNSUPPORTED:
        _say(f"Note: Odoo {version} no longer receives fixes from Odoo S.A. Use this sandbox to "
             "test and migrate, never for real data.")
    if version in AMD64_ONLY and platform.machine().lower() in ("arm64", "aarch64"):
        _say(f"Note: the Odoo {version} image is amd64-only; it runs emulated on this ARM "
             "machine (slower, first start can take several minutes).")
    _say(f"[1/4] Downloading images (first run: ~1-2 GB) — {env['ODOO_IMAGE']}")
    env = box.pull(env, args.registry)
    _say("[2/4] Starting PostgreSQL + Odoo")
    box.compose("up", "-d")
    url = f"http://localhost:{env['ODOO_PORT']}"
    _say(f"[3/4] Waiting for Odoo on {url}")
    info = wait_for_odoo(url, args.timeout)
    db = env["ODOO_DB"]
    if db in (rpc(url, "db", "list", []) or []):
        _say(f"[4/4] Database '{db}' already exists — reusing it")
    else:
        _say(f"[4/4] Creating database '{db}' (demo data: "
             f"{'yes' if env['ODOO_DEMO'] == '1' else 'no'}). This takes 1-5 minutes.")
        rpc(url, "db", "create_database",
            [env["ODOO_MASTER_PASSWORD"], db, env["ODOO_DEMO"] == "1", env["ODOO_LANG"],
             env["ODOO_ADMIN_PASSWORD"], env["ODOO_ADMIN_LOGIN"]],
            timeout=args.timeout * 4)
    uid = rpc(url, "common", "authenticate",
              [db, env["ODOO_ADMIN_LOGIN"], env["ODOO_ADMIN_PASSWORD"], {}])
    if not uid:
        raise SandboxError("The database exists but the admin login failed.")
    env["ODOO_READY"] = "1"  # from now on version/db/lang/demo are fixed
    box.write_env(env)
    summary = {
        "status": "ready",
        "odoo_version": info.get("server_version", env["ODOO_VERSION"]),
        "edition": "Community (CE)",
        "url": url,
        "database": db,
        "login": env["ODOO_ADMIN_LOGIN"],
        "password": f"ODOO_ADMIN_PASSWORD in {box.env_file} (not printed)",
        "image": env["ODOO_IMAGE"],
        "directory": str(box.dir),
    }
    _say("\nSandbox ready:\n" + json.dumps(summary, indent=2))
    _say("\nThis sandbox is Odoo Community. Transgenia cannot provide Odoo Enterprise or "
         "Odoo Online instances; connect your own subscription to use them.")
    _say("\n" + SUPPORT)
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    box = Sandbox(Path(args.dir))
    env = read_env(box.env_file)
    if not env:
        _say(json.dumps({"status": "absent", "directory": str(box.dir)}, indent=2))
        return 0
    compose_command()
    check_docker_running()
    state = "running" if box.running() else "stopped"
    summary: dict[str, Any] = {"status": state, "directory": str(box.dir),
                               "url": f"http://localhost:{env.get('ODOO_PORT')}",
                               "database": env.get("ODOO_DB"),
                               "odoo_version": env.get("ODOO_VERSION"),
                               "image": env.get("ODOO_IMAGE")}
    if state == "running":
        try:
            summary["server_version"] = rpc(summary["url"], "common", "version", [],
                                            timeout=10).get("server_version")
        except (*NOT_READY, SandboxError):
            summary["status"] = "starting"
    _say(json.dumps(summary, indent=2))
    return 0


def cmd_down(args: argparse.Namespace) -> int:
    box = Sandbox(Path(args.dir))
    if not box.compose_file.is_file():
        raise SandboxError(f"No sandbox in {box.dir}.")
    box.compose("stop")
    _say("Sandbox stopped. Data is kept; `sandbox up` starts it again.")
    return 0


def cmd_destroy(args: argparse.Namespace) -> int:
    box = Sandbox(Path(args.dir))
    if not args.yes:
        raise SandboxError("This deletes the sandbox database and files. "
                           "Re-run with --yes to confirm.")
    if box.compose_file.is_file():
        box.compose("down", "--volumes", "--remove-orphans")
    for path in (box.env_file, box.compose_file, box.conf_file):
        if path.exists():
            path.unlink()
    if box.dir.is_dir() and not any(box.dir.iterdir()):
        box.dir.rmdir()
    _say("Sandbox destroyed (containers, volumes and files removed).")
    return 0


def cmd_logs(args: argparse.Namespace) -> int:
    box = Sandbox(Path(args.dir))
    if not box.compose_file.is_file():
        raise SandboxError(f"No sandbox in {box.dir}.")
    box.compose("logs", "--tail", str(args.tail), "odoo")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="deploy_local.py", description=__doc__.split("\n")[0])
    top = parser.add_subparsers(dest="area", required=True)
    sandbox = top.add_parser("sandbox", help="local Odoo sandbox (Docker)")
    sub = sandbox.add_subparsers(dest="action", required=True)

    def common(p: argparse.ArgumentParser) -> argparse.ArgumentParser:
        p.add_argument("--dir", default=str(DEFAULT_DIR), help=f"default: {DEFAULT_DIR}")
        return p

    up = common(sub.add_parser("up", help="create or start the sandbox"))
    # Defaults are applied in Sandbox.prepare so a plain `sandbox up` keeps the
    # values of an existing sandbox instead of resetting them.
    up.add_argument("--odoo", choices=ODOO_VERSIONS,
                    help=f"Odoo version (default: current, or {DEFAULT_VERSION})")
    up.add_argument("--port", type=int, help=f"default: current, or {DEFAULT_PORT}")
    up.add_argument("--db", help=f"database name (default: {DEFAULT_DB})")
    up.add_argument("--lang", help=f"e.g. es_MX (default: {DEFAULT_LANG})")
    up.add_argument("--no-demo", action="store_true", help="skip Odoo demo data")
    up.add_argument("--registry", choices=sorted(REGISTRIES), default="transgenia")
    up.add_argument("--timeout", type=float, default=300.0, help="seconds to wait for Odoo")
    up.set_defaults(func=cmd_up)

    common(sub.add_parser("status", help="show the sandbox state")).set_defaults(
        func=cmd_status)
    common(sub.add_parser("down", help="stop it, keep the data")).set_defaults(func=cmd_down)
    destroy = common(sub.add_parser("destroy", help="delete containers, data and files"))
    destroy.add_argument("--yes", action="store_true")
    destroy.set_defaults(func=cmd_destroy)
    logs = common(sub.add_parser("logs", help="last Odoo log lines"))
    logs.add_argument("--tail", type=int, default=100)
    logs.set_defaults(func=cmd_logs)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except SandboxError as exc:
        print(f"ERROR: {exc}\n\n{SUPPORT}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
